json.id comic.id
json.title comic.title
json.writer comic.writer
json.illustrator comic.illustrator
json.year comic.year
json.genre comic.genre
json.image_url comic.image_url
json.created_at comic.created_at
json.updated_at comic.updated_at
